# Generated by Django 2.2.4 on 2019-10-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teppan', models.CharField(default='0', max_length=140)),
                ('sushi', models.CharField(default='0', max_length=140)),
                ('bar', models.CharField(default='0', max_length=140)),
                ('busser', models.CharField(default='0', max_length=140)),
                ('tip', models.CharField(blank=True, max_length=140)),
                ('total', models.CharField(default='0', max_length=140)),
            ],
        ),
    ]
